[platformio]
default_envs = esp32dev

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
  dht sensor library
  madhephaestus/ESP32Servo@^3.0.5
